export enum NoteProgress {
  TH = 'STUDENTS.PROGRESS.TH',
  HL = 'STUDENTS.PROGRESS.HL',
  HD = 'STUDENTS.PROGRESS.HD',
  CO = 'STUDENTS.PROGRESS.CO',
  BL = 'STUDENTS.PROGRESS.BL',
  TF = 'STUDENTS.PROGRESS.TF',
}
